# Build the project using the Bitcraze builder docker image
name: Nightly

on:
  workflow_dispatch:
  schedule:
  - cron:  '0 0 * * *'


jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        platform: [cf2, tag, bolt]

    env:
      PLATFORM: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v2

    - name: Check and build
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: docker run --rm -v ${PWD}:/module -e "GH_TOKEN=$GH_TOKEN" bitcraze/builder ./tools/build/build $PLATFORM nightly

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2.1.4
      with:
        name: nightly
        path: firmware-${{ matrix.platform }}-nightly.zip
