# Build the project using the Bitcraze builder docker image
# Using definition in nightly-experiment.yml
name: Nightly experiment

on:
  workflow_dispatch:
  schedule:
  - cron:  '25 1 * * *'


jobs:
  read_targets_from_file:
    uses: bitcraze/workflows/.github/workflows/read_build_targets.yml@dfbc8c23a8ec6d4925d01deb20277839ad1235f1
    with:
      target_file: './build_targets.json'

  build:
    needs: read_targets_from_file
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ${{fromJson(needs.read_targets_from_file.outputs.platforms)}}

    env:
      PLATFORM: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v4

    - name: Check and build
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: docker run --rm -v ${PWD}:/module -e "GH_TOKEN=$GITHUB_TOKEN" bitcraze/builder ./tools/build/build $PLATFORM nightly-experiment
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: nightly-experiment
        path: firmware-${{ matrix.platform }}-nightly-experiment.zip
