# Build the project using the Bitcraze builder docker image
name: Nightly

on:
  workflow_dispatch:
  schedule:
  - cron:  '10 1 * * *'


jobs:
  read_targets_from_file:
    uses: bitcraze/workflows/.github/workflows/read_build_targets.yml@a5173df779e4b0b9c1f57d156cda9b8006901fd2
    with:
      target_file: './build_targets.json'

  build:
    needs: read_targets_from_file
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        ${{fromJson(needs.read_targets_from_file.outputs.platforms)}}

    env:
      PLATFORM: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v4

    - name: Check and build
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: docker run --rm -v ${PWD}:/module -e "GH_TOKEN=$GH_TOKEN" bitcraze/builder ./tools/build/build $PLATFORM nightly

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: nightly
        path: firmware-${{ matrix.platform }}-nightly.zip
